#ifndef SIMPLESWITCH_H
#define SIMPLESWITCH_H

#include <QTimer>

// this file is generated by REPC compiler
#include "rep_simpleswitch_source.h"

class SimpleSwitch : public SimpleSwitchSimpleSource
{
    Q_OBJECT
public:
    SimpleSwitch(QObject* parent = nullptr);
    ~SimpleSwitch() override;

    void server_slot(bool clientState) override;

    void timeout_slot();

private:
    QTimer *m_stateChangeTimer;
};

#endif // SIMPLESWITCH_H
